### PR TITLE
Disallow `autovalue.shaded.*` imports

### PR DESCRIPTION
**Pull request by Stephan202**
Suggested commit message:
```
Disallow `autovalue.shaded.*` imports (#774)
```

### CODE REVIEW

**Review by rickie — APPROVED** [review]
What specific situation made you open this PR 😄?

**Comment by rickie** [comment]
@mohamedsamehsalah Do you have time to review this one :)?

**Comment by Stephan202** [comment]
> What specific situation made you open this PR 😄?

Don't remember for sure, but probably an automatic import of some `autovalue.shaded.com.google.common.**` type.

**Review by mohamedsamehsalah — APPROVED** [review]

**Comment by mohamedsamehsalah** [comment]
> @rickie @mohamedsamehsalah Do you have time to review this one :)?

Done ✅

**Pull request merged**
