### PR TITLE
Improve `IdentityConversion` check

### PR DESCRIPTION
**Pull request by Stephan202**
Resolves an issue found while testing Error Prone Support against Checkstyle (currently testing on [this branch](https://github.com/PicnicSupermarket/error-prone-support/compare/sschroevers/integration-tests)).

Suggested commit message:
```
Improve `IdentityConversion` check (#407)

If the result of an explicit boxing operation is immediately
dereferenced, then the explicit conversion operation is not redundant.
```

### CODE REVIEW

**Review by rickie — APPROVED** [review]
Pretty fun edge case. Fix looks good to me.

**Review by chamil-prabodha — APPROVED** [review]

**Comment by rickie** [comment]
Hmm, is this an `improvement` or a `bug fix`?

**Comment by Stephan202** [comment]
- Label-wise: bug fix :+1:
- Suggested commit wise: would leave as-is.

**Comment by rickie** [comment]
Ah yes I only meant label-wise 😄. Nice.

**Pull request merged**
