### PR TITLE
Upgrade Error Prone 2.26.1 -> 2.27.1

### PR DESCRIPTION
**Pull request by Stephan202**
Suggested commit message:
```
Upgrade Error Prone 2.26.1 -> 2.27.1 (#1155)

See:
- https://github.com/google/error-prone/releases/tag/v2.27.0
- https://github.com/google/error-prone/releases/tag/v2.27.1
- https://github.com/google/error-prone/compare/v2.26.1...v2.27.1
- https://github.com/PicnicSupermarket/error-prone/compare/v2.26.1-picnic-2...v2.27.1-picnic-1
```

~Already opening the PR, but planning to also update the compatibility matrix.~ Done.

### CODE REVIEW

**Review by mohamedsamehsalah — APPROVED** [review]
🚀

**Comment by Stephan202** [comment]
Rebased and upgraded further.

**Review by rickie — APPROVED** [review]
I think it's safe to assume that `2.27.1` is also compatible with the same EPS versions?

**Comment by Stephan202** [comment]
Ah good one, I should regenerate the compatibility matrix. Maybe tonight. But yes it will be :)

(Let's leave this PR open for a tiny bit longer then.)

**Pull request merged**
