### PR TITLE
Exclude `error-prone-{experimental,guidelines}` checks from integration tests

### PR DESCRIPTION
**Pull request by rickie**

### CODE REVIEW

**Review by oxkitsune — APPROVED** [review]

**Review by oxkitsune — DISMISSED** [review]
The `{experimental,guidelines}` doesn't expand properly in the find syntax

**Review by Stephan202 — APPROVED** [review]
Added a commit. Suggested commit message:
```
Exclude `error-prone-{experimental,guidelines}` checks from integration tests (#1060)
```

**Review by benhalasi — APPROVED** [review]
On mac, it works like a charm ✅

**Pull request merged**
